[project]
name = 'Decentralized-Humanitarian-Aid-Distribution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donor-verification]
path = 'contracts/donor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-measurement]
path = 'contracts/impact-measurement.clar'
clarity_version = 2
epoch = 2.5

[contracts.recipient-verification]
path = 'contracts/recipient-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
